name: Authing JS SDK Github CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please enter your github name'
        required: true
      email:
        description: 'Please enter your github email'
        required: true
      version:
        description: 'Please enter your release version'
        required: true

jobs:

  readyGo:

    runs-on: ubuntu-latest

    container:
      image: node:12.14.0

    env: 
      PUBLISH_OPTS: ${{ github.ref_name == 'master' && '--verbose' || '--verbose --tag=alpha' }}
      ALIYUN_ACCESS_KEY: ${{ secrets.ALIYUN_ACCESS_KEY }}
      ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      OSS_REGION_PROD: ${{ secrets.OSS_REGION_PROD }}
      CDN_OSS_PROD: ${{ secrets.CDN_OSS_PROD }}

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          
      - name: before scripts
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          echo "Current publish version: ${{ github.event.inputs.version }}"
          echo "Current user.name: ${{ github.event.inputs.name }}"
          echo "Current user.email: ${{ github.event.inputs.email }}"

      - name: set git config
        if: ${{ github.ref_name == 'master' }}
        run: |
          git config --global user.email ${{ github.event.inputs.email }}
          git config --global user.name ${{ github.event.inputs.name }}

      - name: publish
        run: |
          npm install yarn -g
          yarn
          npm run build
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm version $VERESION
          npm publish $PUBLISH_OPTS
          echo "ËÆ∞ÂæóÂêåÊ≠• taobao Ê∫êÂì¶Ôºö https://npm.taobao.org/sync/authing-js-sdk üöÄ"
        env:
          VERESION: ${{ github.event.inputs.version }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: setup oss
        if: ${{ github.ref_name == 'master' }}
        uses: yizhoumo/setup-ossutil@v1
        with: 
          ossutil-version: '1.7.0' # Optional, default to '1.7.0'
          endpoint: ${{ secrets.OSS_REGION_PROD }}
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      
      - name: upload oss
        if: ${{ github.ref_name == 'master' }}
        run: |
          echo "‰∏ä‰º†ÊâìÂåÖÂà∞ CDN"
          echo "VERSION: ${{ github.event.inputs.version }}"
          ossutil cp -f -r build oss://$CDN_OSS_PROD/packages/authing-js-sdk/$VERESION/
        env:
          VERESION: ${{ github.event.inputs.version }}
    
      - name: release
        uses: actions/github-script@v3
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.VERESION }}",
              sha: context.sha
            })
        env:
          VERESION: ${{ github.event.inputs.version }}
